// Apple Design System Colors
export const theme = {
  colors: {
    primary: '#0066cc',
    primaryFocus: '#0071e3',
    primaryOnDark: '#2997ff',
    ink: '#1d1d1f',
    body: '#1d1d1f',
    bodyOnDark: '#ffffff',
    bodyMuted: '#cccccc',
    inkMuted80: '#333333',
    inkMuted48: '#7a7a7a',
    dividerSoft: '#f0f0f0',
    hairline: '#e0e0e0',
    canvas: '#ffffff',
    canvasParchment: '#f5f5f7',
    surfacePearl: '#fafafc',
    surfaceTile1: '#272729',
    surfaceTile2: '#2a2a2c',
    surfaceTile3: '#252527',
    surfaceBlack: '#000000',
    surfaceChipTranslucent: '#d2d2d7',
    onPrimary: '#ffffff',
    onDark: '#ffffff',
    success: '#34c759',
    warning: '#ff9500',
    danger: '#ff3b30',
  },
  typography: {
    display: {
      fontSize: '40px',
      fontWeight: 600,
      lineHeight: '1.1',
      fontFamily: 'SF Pro Display, system-ui, -apple-system, sans-serif',
    },
    headline: {
      fontSize: '28px',
      fontWeight: 600,
      lineHeight: '1.14',
      fontFamily: 'SF Pro Display, system-ui, -apple-system, sans-serif',
    },
    title: {
      fontSize: '21px',
      fontWeight: 600,
      lineHeight: '1.19',
      fontFamily: 'SF Pro Display, system-ui, -apple-system, sans-serif',
    },
    body: {
      fontSize: '17px',
      fontWeight: 400,
      lineHeight: '1.47',
      fontFamily: 'SF Pro Text, system-ui, -apple-system, sans-serif',
    },
    bodyStrong: {
      fontSize: '17px',
      fontWeight: 600,
      lineHeight: '1.24',
      fontFamily: 'SF Pro Text, system-ui, -apple-system, sans-serif',
    },
    caption: {
      fontSize: '14px',
      fontWeight: 400,
      lineHeight: '1.43',
      fontFamily: 'SF Pro Text, system-ui, -apple-system, sans-serif',
    },
    captionStrong: {
      fontSize: '14px',
      fontWeight: 600,
      lineHeight: '1.29',
      fontFamily: 'SF Pro Text, system-ui, -apple-system, sans-serif',
    },
  },
  spacing: {
    xs: '4px',
    sm: '8px',
    md: '16px',
    lg: '24px',
    xl: '32px',
    xxl: '48px',
  },
  radius: {
    sm: '4px',
    md: '8px',
    lg: '12px',
    xl: '16px',
  },
};
