// <auto-generated />
using System;
using API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516235326_MakeStringsUnicode")]
    partial class MakeStringsUnicode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Aim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Aims__3214EC0793FD8D38");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("UserId");

                    b.ToTable("Aims");
                });

            modelBuilder.Entity("API.Models.BlacklistedToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Blacklis__3214EC078E1AA827");

                    b.ToTable("BlacklistedTokens");
                });

            modelBuilder.Entity("API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC070D88E6BD");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("API.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("UsdExchangeRate")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("Id")
                        .HasName("PK__Currenci__3214EC0744C77311");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("API.Models.Frequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IntervalUnitId")
                        .HasColumnType("int");

                    b.Property<int>("IntervalValue")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Frequenc__3214EC0734943CC1");

                    b.HasIndex("IntervalUnitId");

                    b.HasIndex("UserId");

                    b.ToTable("Frequencies");
                });

            modelBuilder.Entity("API.Models.IntervalUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Interval__3213E83F513E4BBA");

                    b.ToTable("IntervalUnits");
                });

            modelBuilder.Entity("API.Models.PlannedTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<int>("FrequencyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(555)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(555)");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("TransactionTypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__PlannedT__3214EC07598C8B65");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("FrequencyId");

                    b.HasIndex("SourceId");

                    b.HasIndex("TransactionTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("PlannedTransactions");
                });

            modelBuilder.Entity("API.Models.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Sources__3214EC07E31F54A0");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("UserId");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("API.Models.SourceAim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AimId")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__SourceAi__3214EC07C10B6095");

                    b.HasIndex("AimId");

                    b.HasIndex("SourceId");

                    b.ToTable("SourceAims");
                });

            modelBuilder.Entity("API.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("DestinationSourceId")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<int>("TransactionTypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Transact__3214EC0728D92CEC");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("DestinationSourceId");

                    b.HasIndex("SourceId");

                    b.HasIndex("TransactionTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("API.Models.TransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Transact__3214EC07B0E1127F");

                    b.ToTable("TransactionTypes");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC0750273533");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105340A5F25EB")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Models.Aim", b =>
                {
                    b.HasOne("API.Models.Currency", "Currency")
                        .WithMany("Aims")
                        .HasForeignKey("CurrencyId")
                        .HasConstraintName("FK__Aims__CurrencyId__656C112C");

                    b.HasOne("API.Models.User", "User")
                        .WithMany("Aims")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Aims__UserId__5070F446");

                    b.Navigation("Currency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.Category", b =>
                {
                    b.HasOne("API.Models.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Categorie__UserI__440B1D61");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.Frequency", b =>
                {
                    b.HasOne("API.Models.IntervalUnit", "IntervalUnitNavigation")
                        .WithMany("Frequencies")
                        .HasForeignKey("IntervalUnitId")
                        .IsRequired()
                        .HasConstraintName("FK__Frequenci__Inter__03F0984C");

                    b.HasOne("API.Models.User", "User")
                        .WithMany("Frequencies")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Frequenci__UserI__01142BA1");

                    b.Navigation("IntervalUnitNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.PlannedTransaction", b =>
                {
                    b.HasOne("API.Models.Category", "Category")
                        .WithMany("PlannedTransactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__PlannedTr__Categ__628FA481");

                    b.HasOne("API.Models.Currency", "Currency")
                        .WithMany("PlannedTransactions")
                        .HasForeignKey("CurrencyId")
                        .IsRequired()
                        .HasConstraintName("FK__PlannedTr__Curre__5FB337D6");

                    b.HasOne("API.Models.Frequency", "Frequency")
                        .WithMany("PlannedTransactions")
                        .HasForeignKey("FrequencyId")
                        .IsRequired()
                        .HasConstraintName("FK__PlannedTr__Frequ__6477ECF3");

                    b.HasOne("API.Models.Source", "Source")
                        .WithMany("PlannedTransactions")
                        .HasForeignKey("SourceId")
                        .IsRequired()
                        .HasConstraintName("FK__PlannedTr__Sourc__6383C8BA");

                    b.HasOne("API.Models.TransactionType", "TransactionType")
                        .WithMany("PlannedTransactions")
                        .HasForeignKey("TransactionTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__PlannedTr__Trans__619B8048");

                    b.HasOne("API.Models.User", "User")
                        .WithMany("PlannedTransactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__PlannedTr__UserI__60A75C0F");

                    b.Navigation("Category");

                    b.Navigation("Currency");

                    b.Navigation("Frequency");

                    b.Navigation("Source");

                    b.Navigation("TransactionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.Source", b =>
                {
                    b.HasOne("API.Models.Currency", "Currency")
                        .WithMany("Sources")
                        .HasForeignKey("CurrencyId")
                        .IsRequired()
                        .HasConstraintName("FK__Sources__Currenc__4D94879B");

                    b.HasOne("API.Models.User", "User")
                        .WithMany("Sources")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Sources__UserId__4CA06362");

                    b.Navigation("Currency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.SourceAim", b =>
                {
                    b.HasOne("API.Models.Aim", "Aim")
                        .WithMany("SourceAims")
                        .HasForeignKey("AimId")
                        .IsRequired()
                        .HasConstraintName("FK__SourceAim__AimId__5535A963");

                    b.HasOne("API.Models.Source", "Source")
                        .WithMany("SourceAims")
                        .HasForeignKey("SourceId")
                        .IsRequired()
                        .HasConstraintName("FK__SourceAim__Sourc__5441852A");

                    b.Navigation("Aim");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("API.Models.Transaction", b =>
                {
                    b.HasOne("API.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Transacti__Categ__59063A47");

                    b.HasOne("API.Models.Currency", "Currency")
                        .WithMany("Transactions")
                        .HasForeignKey("CurrencyId")
                        .IsRequired()
                        .HasConstraintName("FK__Transacti__Curre__5BE2A6F2");

                    b.HasOne("API.Models.Source", "DestinationSource")
                        .WithMany("TransactionDestinationSources")
                        .HasForeignKey("DestinationSourceId")
                        .HasConstraintName("FK__Transacti__Desti__5AEE82B9");

                    b.HasOne("API.Models.Source", "Source")
                        .WithMany("TransactionSources")
                        .HasForeignKey("SourceId")
                        .IsRequired()
                        .HasConstraintName("FK__Transacti__Sourc__59FA5E80");

                    b.HasOne("API.Models.TransactionType", "TransactionType")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Transacti__Trans__5CD6CB2B");

                    b.HasOne("API.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Transacti__UserI__5812160E");

                    b.Navigation("Category");

                    b.Navigation("Currency");

                    b.Navigation("DestinationSource");

                    b.Navigation("Source");

                    b.Navigation("TransactionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.Aim", b =>
                {
                    b.Navigation("SourceAims");
                });

            modelBuilder.Entity("API.Models.Category", b =>
                {
                    b.Navigation("PlannedTransactions");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("API.Models.Currency", b =>
                {
                    b.Navigation("Aims");

                    b.Navigation("PlannedTransactions");

                    b.Navigation("Sources");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("API.Models.Frequency", b =>
                {
                    b.Navigation("PlannedTransactions");
                });

            modelBuilder.Entity("API.Models.IntervalUnit", b =>
                {
                    b.Navigation("Frequencies");
                });

            modelBuilder.Entity("API.Models.Source", b =>
                {
                    b.Navigation("PlannedTransactions");

                    b.Navigation("SourceAims");

                    b.Navigation("TransactionDestinationSources");

                    b.Navigation("TransactionSources");
                });

            modelBuilder.Entity("API.Models.TransactionType", b =>
                {
                    b.Navigation("PlannedTransactions");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Navigation("Aims");

                    b.Navigation("Categories");

                    b.Navigation("Frequencies");

                    b.Navigation("PlannedTransactions");

                    b.Navigation("Sources");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
