// <auto-generated />
using System;
using FinancialPlanner.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinancialPlanner.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260823215320_SeedLookupData")]
    partial class SeedLookupData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.Aim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK__Aims__3214EC0793FD8D38");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("UserId");

                    b.ToTable("Aims");
                });

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.BlacklistedToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id")
                        .HasName("PK__Blacklis__3214EC078E1AA827");

                    b.ToTable("BlacklistedTokens");
                });

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC070D88E6BD");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("UsdExchangeRate")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("Id")
                        .HasName("PK__Currenci__3214EC0744C77311");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "UAH",
                            UsdExchangeRate = 0.0224m
                        },
                        new
                        {
                            Id = 2,
                            Name = "USD",
                            UsdExchangeRate = 1.0000m
                        },
                        new
                        {
                            Id = 3,
                            Name = "EUR",
                            UsdExchangeRate = 1.1685m
                        });
                });

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.Frequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IntervalUnitId")
                        .HasColumnType("integer");

                    b.Property<int>("IntervalValue")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK__Frequenc__3214EC0734943CC1");

                    b.HasIndex("IntervalUnitId");

                    b.HasIndex("UserId");

                    b.ToTable("Frequencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IntervalUnitId = 2,
                            IntervalValue = 1,
                            Name = "Week"
                        },
                        new
                        {
                            Id = 2,
                            IntervalUnitId = 2,
                            IntervalValue = 2,
                            Name = "Two Weeks"
                        },
                        new
                        {
                            Id = 3,
                            IntervalUnitId = 1,
                            IntervalValue = 1,
                            Name = "Day"
                        },
                        new
                        {
                            Id = 4,
                            IntervalUnitId = 3,
                            IntervalValue = 1,
                            Name = "Month"
                        },
                        new
                        {
                            Id = 5,
                            IntervalUnitId = 4,
                            IntervalValue = 1,
                            Name = "Year"
                        });
                });

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.IntervalUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Interval__3213E83F513E4BBA");

                    b.ToTable("IntervalUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Day"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Week"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Month"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Year"
                        });
                });

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.PlannedTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer");

                    b.Property<int>("FrequencyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(555)
                        .IsUnicode(true)
                        .HasColumnType("character varying(555)");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TransactionTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK__PlannedT__3214EC07598C8B65");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("FrequencyId");

                    b.HasIndex("SourceId");

                    b.HasIndex("TransactionTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("PlannedTransactions");
                });

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK__Sources__3214EC07E31F54A0");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("UserId");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.SourceAim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AimId")
                        .HasColumnType("integer");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK__SourceAi__3214EC07C10B6095");

                    b.HasIndex("AimId");

                    b.HasIndex("SourceId");

                    b.ToTable("SourceAims");
                });

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsUnicode(true)
                        .HasColumnType("text");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DestinationSourceId")
                        .HasColumnType("integer");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer");

                    b.Property<int>("TransactionTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK__Transact__3214EC0728D92CEC");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("DestinationSourceId");

                    b.HasIndex("SourceId");

                    b.HasIndex("TransactionTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.TransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id")
                        .HasName("PK__Transact__3214EC07B0E1127F");

                    b.ToTable("TransactionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Expense"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Income"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Transfer"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Adjustment"
                        });
                });

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC0750273533");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105340A5F25EB")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.Aim", b =>
                {
                    b.HasOne("FinancialPlanner.Domain.Entities.Currency", "Currency")
                        .WithMany("Aims")
                        .HasForeignKey("CurrencyId")
                        .HasConstraintName("FK__Aims__CurrencyId__656C112C");

                    b.HasOne("FinancialPlanner.Domain.Entities.User", "User")
                        .WithMany("Aims")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Aims__UserId__5070F446");

                    b.Navigation("Currency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.Category", b =>
                {
                    b.HasOne("FinancialPlanner.Domain.Entities.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Categorie__UserI__440B1D61");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.Frequency", b =>
                {
                    b.HasOne("FinancialPlanner.Domain.Entities.IntervalUnit", "IntervalUnitNavigation")
                        .WithMany("Frequencies")
                        .HasForeignKey("IntervalUnitId")
                        .IsRequired()
                        .HasConstraintName("FK__Frequenci__Inter__03F0984C");

                    b.HasOne("FinancialPlanner.Domain.Entities.User", "User")
                        .WithMany("Frequencies")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Frequenci__UserI__01142BA1");

                    b.Navigation("IntervalUnitNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.PlannedTransaction", b =>
                {
                    b.HasOne("FinancialPlanner.Domain.Entities.Category", "Category")
                        .WithMany("PlannedTransactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__PlannedTr__Categ__628FA481");

                    b.HasOne("FinancialPlanner.Domain.Entities.Currency", "Currency")
                        .WithMany("PlannedTransactions")
                        .HasForeignKey("CurrencyId")
                        .IsRequired()
                        .HasConstraintName("FK__PlannedTr__Curre__5FB337D6");

                    b.HasOne("FinancialPlanner.Domain.Entities.Frequency", "Frequency")
                        .WithMany("PlannedTransactions")
                        .HasForeignKey("FrequencyId")
                        .IsRequired()
                        .HasConstraintName("FK__PlannedTr__Frequ__6477ECF3");

                    b.HasOne("FinancialPlanner.Domain.Entities.Source", "Source")
                        .WithMany("PlannedTransactions")
                        .HasForeignKey("SourceId")
                        .IsRequired()
                        .HasConstraintName("FK__PlannedTr__Sourc__6383C8BA");

                    b.HasOne("FinancialPlanner.Domain.Entities.TransactionType", "TransactionType")
                        .WithMany("PlannedTransactions")
                        .HasForeignKey("TransactionTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__PlannedTr__Trans__619B8048");

                    b.HasOne("FinancialPlanner.Domain.Entities.User", "User")
                        .WithMany("PlannedTransactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__PlannedTr__UserI__60A75C0F");

                    b.Navigation("Category");

                    b.Navigation("Currency");

                    b.Navigation("Frequency");

                    b.Navigation("Source");

                    b.Navigation("TransactionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.Source", b =>
                {
                    b.HasOne("FinancialPlanner.Domain.Entities.Currency", "Currency")
                        .WithMany("Sources")
                        .HasForeignKey("CurrencyId")
                        .IsRequired()
                        .HasConstraintName("FK__Sources__Currenc__4D94879B");

                    b.HasOne("FinancialPlanner.Domain.Entities.User", "User")
                        .WithMany("Sources")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Sources__UserId__4CA06362");

                    b.Navigation("Currency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.SourceAim", b =>
                {
                    b.HasOne("FinancialPlanner.Domain.Entities.Aim", "Aim")
                        .WithMany("SourceAims")
                        .HasForeignKey("AimId")
                        .IsRequired()
                        .HasConstraintName("FK__SourceAim__AimId__5535A963");

                    b.HasOne("FinancialPlanner.Domain.Entities.Source", "Source")
                        .WithMany("SourceAims")
                        .HasForeignKey("SourceId")
                        .IsRequired()
                        .HasConstraintName("FK__SourceAim__Sourc__5441852A");

                    b.Navigation("Aim");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("FinancialPlanner.Domain.Entities.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Transacti__Categ__59063A47");

                    b.HasOne("FinancialPlanner.Domain.Entities.Currency", "Currency")
                        .WithMany("Transactions")
                        .HasForeignKey("CurrencyId")
                        .IsRequired()
                        .HasConstraintName("FK__Transacti__Curre__5BE2A6F2");

                    b.HasOne("FinancialPlanner.Domain.Entities.Source", "DestinationSource")
                        .WithMany("TransactionDestinationSources")
                        .HasForeignKey("DestinationSourceId")
                        .HasConstraintName("FK__Transacti__Desti__5AEE82B9");

                    b.HasOne("FinancialPlanner.Domain.Entities.Source", "Source")
                        .WithMany("TransactionSources")
                        .HasForeignKey("SourceId")
                        .IsRequired()
                        .HasConstraintName("FK__Transacti__Sourc__59FA5E80");

                    b.HasOne("FinancialPlanner.Domain.Entities.TransactionType", "TransactionType")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Transacti__Trans__5CD6CB2B");

                    b.HasOne("FinancialPlanner.Domain.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Transacti__UserI__5812160E");

                    b.Navigation("Category");

                    b.Navigation("Currency");

                    b.Navigation("DestinationSource");

                    b.Navigation("Source");

                    b.Navigation("TransactionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.Aim", b =>
                {
                    b.Navigation("SourceAims");
                });

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.Category", b =>
                {
                    b.Navigation("PlannedTransactions");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.Currency", b =>
                {
                    b.Navigation("Aims");

                    b.Navigation("PlannedTransactions");

                    b.Navigation("Sources");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.Frequency", b =>
                {
                    b.Navigation("PlannedTransactions");
                });

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.IntervalUnit", b =>
                {
                    b.Navigation("Frequencies");
                });

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.Source", b =>
                {
                    b.Navigation("PlannedTransactions");

                    b.Navigation("SourceAims");

                    b.Navigation("TransactionDestinationSources");

                    b.Navigation("TransactionSources");
                });

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.TransactionType", b =>
                {
                    b.Navigation("PlannedTransactions");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinancialPlanner.Domain.Entities.User", b =>
                {
                    b.Navigation("Aims");

                    b.Navigation("Categories");

                    b.Navigation("Frequencies");

                    b.Navigation("PlannedTransactions");

                    b.Navigation("Sources");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
